const SIGN_IN = "SIGN_IN";
const SIGN_UP = "SIGN_UP";
const GET_SMS = "GET_SMS";
const UPDATE_PROFILE = "UPDATE_PROFILE";
const GET_PROFILE = "GET_PROFILE";
const GET_STATISTICS = "GET_STATISTICS";
const GET_NEXT_QUESTION = "GET_NEXT_QUESTION";
const GET_ERRORS = "GET_ERRORS";
const CLEAN_ERRORS = "CLEAN_ERRORS";
const CONNECT_TO_GAME = "CONNECT_TO_GAME";
const SAVE_SOCKET = "SAVE_SOCKET";
const FETCH_QUESTION = "FETCH_QUESTION";
const FETCH_USER = "FETCH_USER";
const FETCH_QUESTIONS = "FETCH_QUESTIONS";
const TOGGLE_BUTTONS = "TOGGLE_BUTTONS";
const ANOTHER_TOGGLE = "ANOTHER_TOGGLE"
const FETCH_SESSION = "FETCH_SESSION";
const SIGN_OUT  = "SIGN_OUT";
const SET_TOKEN = "SET_TOKEN";
const TOGGLE_DRAWER = "TOGGLE_DRAWER";
const NEW_GAME = "NEW_GAME";

const PREVIEW_STARTED = "PREVIEW_STARTED";
const ANSWERS_GETTED = "ANSWERS_GETTED";

const GAME_STARTED_T = "GAME_STARTED";
const BUTTON_PRESSED_T = "BUTTON_PRESSED";
const ANSWER_GETTED_T = "ANSWER_GETTED";

export {
    SIGN_IN,
    SIGN_UP,
    GET_SMS,
    UPDATE_PROFILE,
    GET_PROFILE,
    GET_STATISTICS,
    GET_NEXT_QUESTION,
    GET_ERRORS,
    CLEAN_ERRORS,
    CONNECT_TO_GAME,
    SAVE_SOCKET,
    FETCH_QUESTION,
    FETCH_USER,
    FETCH_QUESTIONS,
    TOGGLE_BUTTONS,
    ANOTHER_TOGGLE,
    GAME_STARTED_T,
    BUTTON_PRESSED_T,
    ANSWER_GETTED_T,
    FETCH_SESSION,
    SIGN_OUT,
    SET_TOKEN,
    ANSWERS_GETTED,
    PREVIEW_STARTED,
    TOGGLE_DRAWER,
    NEW_GAME
}
